// Import stylesheets
import './style.css';
import _ from 'lodash';

// Import Formio Export Tools Library
import FormioExport from './src';

// Import helper functions
import { getRandomId, getDate, createIframe } from './helpers';

// Get the app div element
const appDiv = document.getElementById('app');

// Define the component using Form.io's Component JSON Schema
let component = {
  input: false,
  components: [
    {
      input: true,
      conditional: {
        show: null,
        eq: '',
        when: null,
      },
      tableView: true,
      disabled: false,
      label: 'First Name',
      id: 'erskkef',
      type: 'textfield',
      key: 'firstName',
      validate: {
        strictDateValidation: false,
        custom: '',
        customPrivate: false,
        unique: false,
        minLength: '',
        multiple: false,
        pattern: '',
        required: true,
        maxLength: '',
      },
      placeholder: '',
      prefix: '',
      customClass: '',
      suffix: '',
      multiple: false,
      defaultValue: null,
      protected: false,
      unique: false,
      persistent: true,
      hidden: false,
      clearOnHide: true,
      refreshOn: '',
      redrawOn: '',
      modalEdit: false,
      dataGridLabel: false,
      labelPosition: 'top',
      description: '',
      errorLabel: '',
      tooltip: '',
      hideLabel: false,
      tabindex: '',
      autofocus: false,
      dbIndex: false,
      customDefaultValue: '',
      calculateValue: '',
      calculateServer: false,
      widget: {
        type: 'input',
      },
      attributes: {},
      validateOn: 'change',
      overlay: {
        style: '',
        left: '',
        top: '',
        width: '',
        height: '',
      },
      allowCalculateOverride: false,
      encrypted: false,
      showCharCount: false,
      showWordCount: false,
      properties: {},
      allowMultipleMasks: false,
      mask: false,
      inputType: 'text',
      inputFormat: 'plain',
      inputMask: '',
      spellcheck: true,
      addons: [],
      displayMask: '',
      truncateMultipleSpaces: false,
    },
    {
      input: true,
      conditional: {
        show: null,
        json: '',
        eq: '',
        when: null,
      },
      tableView: true,
      disabled: false,
      label: 'Middle Initial',
      id: 'e28s9mj',
      type: 'textfield',
      key: 'middleInitial',
      validate: {
        strictDateValidation: false,
        custom: '',
        customPrivate: false,
        minLength: '',
        unique: false,
        pattern: '',
        multiple: false,
        customMessage: '',
        json: '',
        required: false,
        maxLength: '',
      },
      customConditional: '',
      placeholder: '',
      prefix: '',
      customClass: '',
      suffix: '',
      multiple: false,
      defaultValue: null,
      protected: false,
      unique: false,
      persistent: true,
      hidden: false,
      clearOnHide: true,
      refreshOn: '',
      redrawOn: '',
      modalEdit: false,
      dataGridLabel: false,
      labelPosition: 'top',
      description: '',
      errorLabel: '',
      tooltip: '',
      hideLabel: false,
      tabindex: '',
      autofocus: false,
      dbIndex: false,
      customDefaultValue: '',
      calculateValue: '',
      calculateServer: false,
      widget: {
        type: 'input',
      },
      attributes: {},
      validateOn: 'change',
      overlay: {
        style: '',
        left: '',
        top: '',
        width: '',
        height: '',
      },
      allowCalculateOverride: false,
      encrypted: false,
      showCharCount: false,
      showWordCount: false,
      properties: {},
      allowMultipleMasks: false,
      mask: false,
      inputType: 'text',
      inputFormat: 'plain',
      inputMask: '',
      spellcheck: true,
      addons: [],
      displayMask: '',
      truncateMultipleSpaces: false,
    },
    {
      input: true,
      conditional: {
        show: null,
        json: '',
        eq: '',
        when: null,
      },
      tableView: true,
      disabled: false,
      label: 'Last Name',
      id: 'ekgdujb',
      type: 'textfield',
      key: 'lastName',
      validate: {
        strictDateValidation: false,
        custom: '',
        customPrivate: false,
        minLength: '',
        unique: false,
        pattern: '',
        multiple: false,
        customMessage: '',
        json: '',
        required: true,
        maxLength: '',
      },
      customConditional: '',
      placeholder: '',
      prefix: '',
      customClass: '',
      suffix: '',
      multiple: false,
      defaultValue: null,
      protected: false,
      unique: false,
      persistent: true,
      hidden: false,
      clearOnHide: true,
      refreshOn: '',
      redrawOn: '',
      modalEdit: false,
      dataGridLabel: false,
      labelPosition: 'top',
      description: '',
      errorLabel: '',
      tooltip: '',
      hideLabel: false,
      tabindex: '',
      autofocus: false,
      dbIndex: false,
      customDefaultValue: '',
      calculateValue: '',
      calculateServer: false,
      widget: {
        type: 'input',
      },
      attributes: {},
      validateOn: 'change',
      overlay: {
        style: '',
        left: '',
        top: '',
        width: '',
        height: '',
      },
      allowCalculateOverride: false,
      encrypted: false,
      showCharCount: false,
      showWordCount: false,
      properties: {},
      allowMultipleMasks: false,
      mask: false,
      inputType: 'text',
      inputFormat: 'plain',
      inputMask: '',
      spellcheck: true,
      addons: [],
      displayMask: '',
      truncateMultipleSpaces: false,
    },
    {
      input: true,
      conditional: {
        show: null,
        json: '',
        eq: '',
        when: null,
      },
      tableView: true,
      disabled: false,
      label: 'Email',
      id: 'eyauvsh',
      type: 'email',
      key: 'email',
      validate: {
        strictDateValidation: false,
        custom: '',
        customPrivate: false,
        minLength: '',
        unique: false,
        pattern: '',
        multiple: false,
        customMessage: '',
        json: '',
        required: true,
        maxLength: '',
      },
      customConditional: '',
      placeholder: '',
      prefix: '',
      customClass: '',
      suffix: '',
      multiple: false,
      defaultValue: null,
      protected: false,
      unique: false,
      persistent: true,
      hidden: false,
      clearOnHide: true,
      refreshOn: '',
      redrawOn: '',
      modalEdit: false,
      dataGridLabel: false,
      labelPosition: 'top',
      description: '',
      errorLabel: '',
      tooltip: '',
      hideLabel: false,
      tabindex: '',
      autofocus: false,
      dbIndex: false,
      customDefaultValue: '',
      calculateValue: '',
      calculateServer: false,
      widget: {
        type: 'input',
      },
      attributes: {},
      validateOn: 'change',
      overlay: {
        style: '',
        left: '',
        top: '',
        width: '',
        height: '',
      },
      allowCalculateOverride: false,
      encrypted: false,
      showCharCount: false,
      showWordCount: false,
      properties: {},
      allowMultipleMasks: false,
      mask: false,
      inputType: 'email',
      inputFormat: 'plain',
      inputMask: '',
      spellcheck: true,
      kickbox: {
        enabled: false,
      },
      addons: [],
      displayMask: '',
      truncateMultipleSpaces: false,
    },
    {
      input: true,
      conditional: {
        show: null,
        json: '',
        eq: '',
        when: null,
      },
      tableView: true,
      disabled: false,
      label: 'Phone Number',
      id: 'eymis0k',
      type: 'phoneNumber',
      key: 'phoneNumber',
      validate: {
        strictDateValidation: false,
        custom: '',
        customPrivate: false,
        unique: false,
        minLength: '',
        multiple: false,
        pattern: '',
        customMessage: '',
        json: '',
        required: true,
        maxLength: '',
      },
      customConditional: '',
      placeholder: '',
      prefix: '',
      customClass: '',
      suffix: '',
      multiple: false,
      defaultValue: null,
      protected: false,
      unique: false,
      persistent: true,
      hidden: false,
      clearOnHide: true,
      refreshOn: '',
      redrawOn: '',
      modalEdit: false,
      dataGridLabel: false,
      labelPosition: 'top',
      description: '',
      errorLabel: '',
      tooltip: '',
      hideLabel: false,
      tabindex: '',
      autofocus: false,
      dbIndex: false,
      customDefaultValue: '',
      calculateValue: '',
      calculateServer: false,
      widget: {
        type: 'input',
      },
      attributes: {},
      validateOn: 'change',
      overlay: {
        style: '',
        left: '',
        top: '',
        width: '',
        height: '',
      },
      allowCalculateOverride: false,
      encrypted: false,
      showCharCount: false,
      showWordCount: false,
      properties: {},
      allowMultipleMasks: false,
      mask: false,
      inputType: 'tel',
      inputFormat: 'plain',
      inputMask: '(999) 999-9999',
      spellcheck: true,
      inputMode: 'decimal',
      addons: [],
      displayMask: '',
      truncateMultipleSpaces: false,
    },
    {
      input: false,
      conditional: {
        show: null,
        json: '',
        eq: '',
        when: null,
      },
      tableView: false,
      disabled: false,
      html: '<p><strong>Address</strong></p>',
      label: 'Content',
      id: 'emyrqjd',
      type: 'content',
      key: 'content',
      validate: {
        strictDateValidation: false,
        multiple: false,
        required: false,
        custom: '',
        customPrivate: false,
        unique: false,
      },
      customConditional: '',
      placeholder: '',
      prefix: '',
      customClass: '',
      suffix: '',
      multiple: false,
      defaultValue: null,
      protected: false,
      unique: false,
      persistent: true,
      hidden: false,
      clearOnHide: true,
      refreshOn: '',
      redrawOn: '',
      modalEdit: false,
      dataGridLabel: false,
      labelPosition: 'top',
      description: '',
      errorLabel: '',
      tooltip: '',
      hideLabel: false,
      tabindex: '',
      autofocus: false,
      dbIndex: false,
      customDefaultValue: '',
      calculateValue: '',
      calculateServer: false,
      widget: null,
      attributes: {},
      validateOn: 'change',
      overlay: {
        style: '',
        left: '',
        top: '',
        width: '',
        height: '',
      },
      allowCalculateOverride: false,
      encrypted: false,
      showCharCount: false,
      showWordCount: false,
      properties: {},
      allowMultipleMasks: false,
      addons: [],
    },
    {
      input: true,
      conditional: {
        show: null,
        json: '',
        eq: '',
        when: null,
      },
      tableView: true,
      disabled: false,
      label: 'Street Address',
      id: 'e24mng8',
      type: 'textfield',
      key: 'address',
      validate: {
        strictDateValidation: false,
        custom: '',
        customPrivate: false,
        minLength: '',
        unique: false,
        pattern: '',
        multiple: false,
        customMessage: '',
        json: '',
        required: true,
        maxLength: '',
      },
      customConditional: '',
      placeholder: '',
      prefix: '',
      customClass: '',
      suffix: '',
      multiple: false,
      defaultValue: null,
      protected: false,
      unique: false,
      persistent: true,
      hidden: false,
      clearOnHide: true,
      refreshOn: '',
      redrawOn: '',
      modalEdit: false,
      dataGridLabel: false,
      labelPosition: 'top',
      description: '',
      errorLabel: '',
      tooltip: '',
      hideLabel: false,
      tabindex: '',
      autofocus: false,
      dbIndex: false,
      customDefaultValue: '',
      calculateValue: '',
      calculateServer: false,
      widget: {
        type: 'input',
      },
      attributes: {},
      validateOn: 'change',
      overlay: {
        style: '',
        left: '',
        top: '',
        width: '',
        height: '',
      },
      allowCalculateOverride: false,
      encrypted: false,
      showCharCount: false,
      showWordCount: false,
      properties: {},
      allowMultipleMasks: false,
      mask: false,
      inputType: 'text',
      inputFormat: 'plain',
      inputMask: '',
      spellcheck: true,
      addons: [],
      displayMask: '',
      truncateMultipleSpaces: false,
    },
    {
      input: true,
      conditional: {
        show: null,
        json: '',
        eq: '',
        when: null,
      },
      tableView: true,
      disabled: false,
      label: 'City',
      id: 'ejq44nn',
      type: 'textfield',
      key: 'city',
      validate: {
        strictDateValidation: false,
        custom: '',
        customPrivate: false,
        minLength: '',
        unique: false,
        pattern: '',
        multiple: false,
        customMessage: '',
        json: '',
        required: true,
        maxLength: '',
      },
      customConditional: '',
      placeholder: '',
      prefix: '',
      customClass: '',
      suffix: '',
      multiple: false,
      defaultValue: null,
      protected: false,
      unique: false,
      persistent: true,
      hidden: false,
      clearOnHide: true,
      refreshOn: '',
      redrawOn: '',
      modalEdit: false,
      dataGridLabel: false,
      labelPosition: 'top',
      description: '',
      errorLabel: '',
      tooltip: '',
      hideLabel: false,
      tabindex: '',
      autofocus: false,
      dbIndex: false,
      customDefaultValue: '',
      calculateValue: '',
      calculateServer: false,
      widget: {
        type: 'input',
      },
      attributes: {},
      validateOn: 'change',
      overlay: {
        style: '',
        left: '',
        top: '',
        width: '',
        height: '',
      },
      allowCalculateOverride: false,
      encrypted: false,
      showCharCount: false,
      showWordCount: false,
      properties: {},
      allowMultipleMasks: false,
      mask: false,
      inputType: 'text',
      inputFormat: 'plain',
      inputMask: '',
      spellcheck: true,
      addons: [],
      displayMask: '',
      truncateMultipleSpaces: false,
    },
    {
      id: 'ekzssyb',
      addons: [],
      allowCalculateOverride: false,
      allowMultipleMasks: false,
      attributes: {},
      authenticate: false,
      autofocus: false,
      calculateServer: false,
      calculateValue: '',
      clearOnHide: true,
      clearOnRefresh: false,
      conditional: {
        eq: '',
        json: '',
        show: null,
        when: null,
      },
      customClass: '',
      customConditional: '',
      customDefaultValue: '',
      customOptions: {},
      data: {
        custom: '',
        json: '',
        resource: '',
        url: '',
        values: [
          {
            label: '',
            value: 'AL',
          },
          {
            label: '',
            value: 'AK',
          },
          {
            label: '',
            value: 'AZ',
          },
          {
            label: '',
            value: 'AR',
          },
          {
            label: '',
            value: 'CA',
          },
          {
            label: '',
            value: 'CO',
          },
          {
            label: '',
            value: 'CT',
          },
          {
            label: '',
            value: 'DE',
          },
          {
            label: '',
            value: 'DC',
          },
          {
            label: '',
            value: 'FL',
          },
          {
            label: '',
            value: 'GA',
          },
          {
            label: '',
            value: 'HI',
          },
          {
            label: '',
            value: 'ID',
          },
          {
            label: '',
            value: 'IL',
          },
          {
            label: '',
            value: 'IN',
          },
          {
            label: '',
            value: 'IA',
          },
          {
            label: '',
            value: 'KS',
          },
          {
            label: '',
            value: 'KY',
          },
          {
            label: '',
            value: 'LA',
          },
          {
            label: '',
            value: 'ME',
          },
          {
            label: '',
            value: 'MD',
          },
          {
            label: '',
            value: 'MA',
          },
          {
            label: '',
            value: 'MI',
          },
          {
            label: '',
            value: 'MN',
          },
          {
            label: '',
            value: 'MS',
          },
          {
            label: '',
            value: 'MO',
          },
          {
            label: '',
            value: 'MT',
          },
          {
            label: '',
            value: 'NE',
          },
          {
            label: '',
            value: 'NV',
          },
          {
            label: '',
            value: 'NH',
          },
          {
            label: '',
            value: 'NJ',
          },
          {
            label: '',
            value: 'NM',
          },
          {
            label: '',
            value: 'NY',
          },
          {
            label: '',
            value: 'NC',
          },
          {
            label: '',
            value: 'ND',
          },
          {
            label: '',
            value: 'OH',
          },
          {
            label: '',
            value: 'OK',
          },
          {
            label: '',
            value: 'OR',
          },
          {
            label: '',
            value: 'PA',
          },
          {
            label: '',
            value: 'RI',
          },
          {
            label: '',
            value: 'SC',
          },
          {
            label: '',
            value: 'SD',
          },
          {
            label: '',
            value: 'TN',
          },
          {
            label: '',
            value: 'TX',
          },
          {
            label: '',
            value: 'UT',
          },
          {
            label: '',
            value: 'VT',
          },
          {
            label: '',
            value: 'VA',
          },
          {
            label: '',
            value: 'WA',
          },
          {
            label: '',
            value: 'WV',
          },
          {
            label: '',
            value: 'WI',
          },
          {
            label: '',
            value: 'WY',
          },
        ],
      },
      dataGridLabel: false,
      dataSrc: 'values',
      dataType: '',
      dbIndex: false,
      defaultValue: '',
      description: '',
      disabled: false,
      encrypted: false,
      errorLabel: '',
      errors: '',
      filter: '',
      fuseOptions: {
        include: 'score',
        threshold: 0.3,
      },
      hidden: false,
      hideLabel: false,
      idPath: 'id',
      ignoreCache: false,
      indexeddb: {
        filter: {},
      },
      input: true,
      key: 'state',
      label: 'State',
      labelMargin: '',
      labelPosition: 'top',
      labelWidth: '',
      lazyLoad: true,
      limit: 100,
      logic: [],
      minSearch: 0,
      modalEdit: false,
      multiple: false,
      overlay: {
        height: '',
        left: '',
        page: '',
        style: '',
        top: '',
        width: '',
      },
      persistent: true,
      placeholder: '',
      prefix: '',
      properties: {},
      protected: false,
      readOnlyValue: false,
      redrawOn: '',
      refreshOn: '',
      refreshOnBlur: '',
      searchDebounce: 0.3,
      searchEnabled: true,
      searchField: '',
      selectFields: '',
      selectThreshold: 0.3,
      showCharCount: false,
      showWordCount: false,
      suffix: '',
      tabindex: '',
      tableView: true,
      tags: [],
      template: '<span>{{ item.value }}</span>',
      tooltip: '',
      type: 'select',
      unique: false,
      uniqueOptions: false,
      useExactSearch: false,
      validate: {
        custom: '',
        customMessage: '',
        customPrivate: false,
        json: '',
        multiple: false,
        onlyAvailableItems: false,
        required: true,
        strictDateValidation: false,
        unique: false,
      },
      validateOn: 'change',
      valueProperty: '',
      widget: 'choicesjs',
    },
    {
      input: true,
      conditional: {
        show: null,
        json: '',
        eq: '',
        when: null,
      },
      tableView: true,
      disabled: false,
      label: 'Zip Code',
      id: 'efa35k',
      type: 'textfield',
      key: 'zipCode',
      validate: {
        strictDateValidation: false,
        custom: '',
        customPrivate: false,
        minLength: '',
        unique: false,
        pattern: '',
        multiple: false,
        customMessage: '',
        json: '',
        required: true,
        maxLength: '',
      },
      customConditional: '',
      placeholder: '',
      prefix: '',
      customClass: '',
      suffix: '',
      multiple: false,
      defaultValue: null,
      protected: false,
      unique: false,
      persistent: true,
      hidden: false,
      clearOnHide: true,
      refreshOn: '',
      redrawOn: '',
      modalEdit: false,
      dataGridLabel: false,
      labelPosition: 'top',
      description: '',
      errorLabel: '',
      tooltip: '',
      hideLabel: false,
      tabindex: '',
      autofocus: false,
      dbIndex: false,
      customDefaultValue: '',
      calculateValue: '',
      calculateServer: false,
      widget: {
        type: 'input',
      },
      attributes: {},
      validateOn: 'change',
      overlay: {
        style: '',
        left: '',
        top: '',
        width: '',
        height: '',
      },
      allowCalculateOverride: false,
      encrypted: false,
      showCharCount: false,
      showWordCount: false,
      properties: {},
      allowMultipleMasks: false,
      mask: false,
      inputType: 'text',
      inputFormat: 'plain',
      inputMask: '',
      spellcheck: true,
      addons: [],
      displayMask: '',
      truncateMultipleSpaces: false,
    },
  ],
  tableView: false,
  label: 'Page 1',
  id: 'eyzwkqg',
  type: 'panel',
  title: 'First Investor',
  key: 'page1',
  placeholder: '',
  prefix: '',
  customClass: '',
  suffix: '',
  multiple: false,
  defaultValue: null,
  protected: false,
  unique: false,
  persistent: false,
  hidden: false,
  clearOnHide: false,
  refreshOn: '',
  redrawOn: '',
  modalEdit: false,
  dataGridLabel: false,
  labelPosition: 'top',
  description: '',
  errorLabel: '',
  tooltip: '',
  hideLabel: false,
  tabindex: '',
  disabled: false,
  autofocus: false,
  dbIndex: false,
  customDefaultValue: '',
  calculateValue: '',
  calculateServer: false,
  widget: null,
  attributes: {},
  validateOn: 'change',
  validate: {
    required: false,
    custom: '',
    customPrivate: false,
    strictDateValidation: false,
    multiple: false,
    unique: false,
  },
  conditional: {
    show: null,
    when: null,
    eq: '',
  },
  overlay: {
    style: '',
    left: '',
    top: '',
    width: '',
    height: '',
  },
  allowCalculateOverride: false,
  encrypted: false,
  showCharCount: false,
  showWordCount: false,
  properties: {},
  allowMultipleMasks: false,
  tree: false,
  theme: 'default',
  breadcrumb: 'default',
  addons: [],
  lazyLoad: false,
};
// Define a Form.io submission
let submission = {
  _id: getRandomId(),
  owner: getRandomId(),
  modified: getDate(),
  data: {
    firstName: 'tarantest',
    middleInitial: '',
    lastName: 'client',
    email: 'itstarantest+client@gmail.com',
    phoneNumber: '(123) 123-1313',
    address: '1111111',
    city: '1',
    state: 'CO',
    zipCode: '12312',
    submit: true,
    trustedContactName: '',
    homeEmail: '',
    status: 'active',
    executorEmail: '',
    cpaPhone: '',
    trustedContactPhone: '',
    familyOfficerPhone: '',
    spouseEmail: '',
    isProspect: false,
    ids: [
      {
        number: '',
        type: '',
        issueDate: null,
        issuer: '',
        expirationDate: null,
      },
    ],
    familyOfficerName: '',
    aum: 0,
    cpaName: '',
    riskTolerance: '',
    advisorId: '503e9c3a-10fb-4f43-b544-862ce19ef1bd',
    cognitoUsername: '71ffac05-4ec5-4c11-a0b7-c0c95704f26c',
    occupation: '',
    spouseName: '',
    mailingState: '',
    createdAt: '2024-03-06T20:48:50.824Z',
    source: 'portal',
    totalInvestments: null,
    executorName: '',
    assets: null,
    familyOfficerEmail: '',
    maritalStatus: '',
    cognitoIdentityId: 'us-east-1:8a85c0ad-80b9-ca7d-3876-682fa6232b7c',
    employerZipCode: '',
    fundsExperience: null,
    insuranceBrokerPhone: '',
    netWorth: null,
    spousePhone: '',
    federalTaxBracket: null,
    isMailingAddressSameAsHomeAddress: true,
    executorPhone: '',
    investableAssets: null,
    riskScore: null,
    trustedContactEmail: '',
    dependents: [
      {
        lastName: '',
        zipCode: '',
        address: '',
        city: '',
        dateOfBirth: null,
        type: '',
        ssn: '',
        firstName: '',
        middleInitial: '',
        phoneNumber: '',
        name: ' ',
        state: '',
        relationship: '',
        email: '',
        sharePercentage: '',
      },
    ],
    annualIncome: '',
    sex: '',
    workPhoneNumber: '',
    attorneyName: '',
    employerState: '',
    firmId: '2a12159d-d50b-4f07-a651-ab501f1ce094',
    goals: [],
    name: 'tarantest client',
    stocksExperience: null,
    attorneyPhone: '',
    mailingCity: '',
    partnershipsExperience: null,
    mailingAddress: '',
    employerAddress: '',
    employerName: '',
    insuranceBrokerEmail: '',
    objective: '',
    homePhoneNumber: '',
    socialMedia: {
      youtube: '',
      homeWebsite: '',
      twitter: '',
      facebook: '',
      workWebsite: '',
      instagram: '',
      linkedin: '',
      otherWebsite: '',
    },
    dateOfBirth: null,
    liquidNetWorth: null,
    id: 'cd0d210b-eac9-472a-bc1d-dc1060328fef',
    beneficiaries: [
      {
        lastName: '',
        zipCode: '',
        address: '',
        city: '',
        dateOfBirth: null,
        type: '',
        ssn: '',
        firstName: '',
        middleInitial: '',
        phoneNumber: '',
        name: ' ',
        state: '',
        relationship: '',
        email: '',
        sharePercentage: '',
      },
    ],
    preferredName: '',
    tags: ['ROTH IRA'],
    employerPhone: '',
    employmentStatus: '',
    settings: {
      emailOn: {
        FORM_CANCELLED: false,
        REVIEWER_SENT: true,
        REVIEWER_REVIEWED: false,
        ENVELOPE_CANCELLED: false,
        ENVELOPE_CREATED: false,
        ENVELOPE_DECLINED: false,
        REVIEWER_DECLINED: false,
        SIGNER_SIGNED: false,
        FORM_SENT: false,
        ENVELOPE_COMPLETED: false,
        FORM_COMPLETED: false,
        FORM_DECLINED: false,
      },
      suppressEmails: false,
    },
    timeHorizon: '',
    residenceValue: null,
    retirementAge: null,
    driversLicenseNumber: '',
    employerCity: '',
    otherExperience: null,
    isVerified: true,
    liabilities: null,
    ssn: '',
    cpaEmail: '',
    insuranceBrokerName: '',
    mailingZipCode: '',
    updatedAt: '2024-03-13T12:51:25.440Z',
    attorneyEmail: '',
    includeSecondInvestor: false,
    workEmail: '',
    type: 'individual',
    firmName: 'Cake Advisory Firm',
  },
};

// Define additional configurations
let options = {
  formio: {
    ignoreLayout: false,
    emptyValue: '-',
  },
};

// Define new instance of FormioExport
const exporter = new FormioExport(component, submission, options);

// Render the component to HTML
document.getElementById('btn-html').addEventListener('click', () => {
  exporter.toHtml().then((html) => {
    html.style.margin = 'auto';
    let iframe = createIframe(appDiv);
    let doc = iframe.contentDocument || iframe.contentWindow.document;
    doc.body.appendChild(html);
  });
});

// Export to PDF data uri string
document.getElementById('btn-pdf').addEventListener('click', () => {
  let config = {
    download: false,
    filename: 'example.pdf',
    html2canvas: {
      logging: true,
      onclone: (doc) => {
        // You can modify the html before converting it to canvas (add additional page breaks, etc)
        console.log('html cloned!', doc);
      },
      onrendered: (canvas) => {
        // You can access the canvas before converting it to PDF
        console.log('html rendered!', canvas);
      },
    },
  };

  exporter.toPdf(config).then((pdf) => {
    console.log('pdf ready', pdf);
    let iframe = createIframe(appDiv);
    iframe.src = pdf.output('datauristring');
  });
});

// Initialize the app by rendering the HTML
document.getElementById('btn-html').click();
